[package]
name = "pure-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
